apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ansible-operator
  namespace: openshift-gitops
spec:
  source:
    repoURL: https://github.com/jwerak/ed-main.git
    targetRevision: HEAD
    path: products/ansible
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
